name: Publish Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Images
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [alpine]
        arch:
          - platform: linux/amd64

    steps:
      - name: Get Current Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}      
      
      - name: Build and Push ${{ matrix.os }} (${{ matrix.arch.platform }})
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ matrix.arch.platform }}
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/pve-discord-proxy:latest